# RAG System Configuration
# Version: 3.0 (Combined Top-K Retrieval)
# Updated: 2025-08-20
# Leaderboard Score: 0.55 (from 0.46, +19.6%)

# Current active version
version: "2300_combined_top"

# File paths (relative to data/rag/)
files:
  chunks: "chunks_2300.json"
  embeddings: "embeddings_2300.npy"
  faiss_index: "faiss_index_2300.index"
  bm25_index: "bm25_index_2300.pkl"
  metadata: "metadata_2300.json"

# Chunking configuration
chunking:
  method: "hybrid"
  chunk_size: 2300
  chunk_overlap: 200
  boundary_overlap: 300
  
# Embedding configuration
embedding:
  model: "nlpai-lab/KURE-v1"
  dimension: 1024
  batch_size: 16
  device: "cuda"

# Search configuration
search:
  # Retriever type: "vector", "bm25", "hybrid", "combined_top"
  retriever_type: "combined_top"  # Best performing approach (0.55 score)
  
  # Combined Top-K configuration (proven best performance)
  combined_top:
    bm25_k: 3      # Top 3 from BM25
    vector_k: 3    # Top 3 from Vector
    deduplicate: false  # Keep duplicates for richer context
  
  # Legacy hybrid weights (for backward compatibility)
  bm25_weight: 0.7  # 70% keyword-based (not used in combined_top)
  vector_weight: 0.3  # 30% vector-based (not used in combined_top)
  
  # Normalization method: "min_max", "rank", "softmax"
  normalization_method: "min_max"
  
  # Reranking configuration
  enable_reranking: false  # Disable reranking for combined_top approach
  
  # Search parameters
  initial_k: 30  # Initial retrieval count (not used when reranking disabled)
  rerank_k: 10   # After reranking (not used when reranking disabled)
  final_k: 6     # Final result count (3 BM25 + 3 Vector)
  direct_k: 6    # Direct retrieval count when reranking is disabled
  
# Performance settings
performance:
  use_gpu: true
  batch_size: 16
  max_memory_gb: 24
  cache_enabled: true

# Old versions (for reference)
old_versions:
  v1:
    version: "512"
    files:
      chunks: "chunks.json"
      embeddings: "embeddings.npy"
      faiss_index: "faiss.index"
      bm25_index: "bm25_index.pkl"
    chunking:
      chunk_size: 512
      chunk_overlap: 50