markdownExploder: true
prd:
  prdFile: docs/prd.md
  prdVersion: v4
  prdSharded: true
  prdShardedLocation: docs/prd
  epicFilePattern: epic-{n}*.md
architecture:
  architectureFile: docs/Architecture.md
  architectureVersion: v7
  architectureSharded: true
  architectureShardedLocation: docs/architecture
customTechnicalDocuments: null
devLoadAlwaysFiles:
  - docs/architecture/2-tech-stack.md
  - docs/architecture/4-components-interface-definitions.md
  - docs/architecture/7-source-tree.md
  - docs/competition-info/2-critical-rules.md
  - docs/pipeline/1-5-training-data-preparation.md
devDebugLog: .ai/debug-log.md
devStoryLocation: docs/stories
slashPrefix: BMad
